### ISSUE TITLE
Support for custom logo on Custos/Keycloak login screen

### ISSUE THREAD

**Issue by jbasney** [apache/airavata-custos#145]
In cases where a Custos client is not using idphint support (#40) to bypass the Custos/Keycloak login screen, it's nice to be able to customize the login screen with a project logo and other theming. Currently the Custos team can manually configure the [Keycloak theme](https://www.keycloak.org/docs/latest/server_development/#_themes) for a tenant, but otherwise I think the logo/theme is not customizable via the Custos tenant management service.

Some possible options for this feature:

1. The [tenant management client API](https://github.com/apache/airavata-custos/blob/master/custos-client-sdks/custos-python-sdk/README.md) includes a logo_uri parameter that could be used for specifying a logo for the tenant. This is a simple option that wouldn't require a lot of CSS customization, I think.
2. The tenant management interface could provide a selection of predefined themes to choose from.
3. The tenant management interface could support upload of CSS/etc. for full theme customization. In my opinion, this option is probably overkill.

**Comment by isururanawaka** [comment]
@jbasney @smarru   Currently, clients fetch opened configuration from Custos endpoints and extract Keycloak authorization endpoint, and directly calls it from the client which loads the Keycloak login page. How about creating a Custos authorization endpoint customized for each client and load the Custos login page and then call Keycloak endpoints instead of calling Keycloak frontend login page.

**Comment by jbasney** [comment]
Sure, if it's better to add a Custos login page versus customizing the Keycloak login page, that's fine with me, so long as it doesn't introduce additional browser redirects into the login process.

**Comment by isururanawaka** [comment]
completed with themes
